### ISSUE TITLE
Mouse factor numeric display shows wrong integer component

### ISSUE THREAD

**Issue by 0joshuaolson1** [Blackvoxel/Blackvoxel#10]
2 -> 2.00 is correct.
1 -> 0.00 is incorrect.
3 -> 2.00 is incorrect.
4 -> 3.00 is incorrect.
I think [this](https://github.com/Blackvoxel/Blackvoxel/blob/master/src/ZGui_NumericChoiceBox.cpp#L92) is the method of interest.

**Comment by Blackvoxel** [comment]
Hi, Joshua

Thank you for signaling this bug.

We reproduced it successfully. We'll publish a patch in the next days.

The Blackvoxel Team

**Comment by Blackvoxel** [comment]
Bug fixed !
