### ISSUE TITLE
Noise when pointing to non-destroy-able voxel while MiningInProgress

### ISSUE THREAD

**Issue by asl97** [Blackvoxel/Blackvoxel#23]
Startling loud noise when pointing to non-destroy-able voxel while MiningInProgress.

Example: place an atomic compressor, place some item in it, point to another voxel that is 'destroy-able', click and hold, move pointer until hover over atomic compressor, 'non-empty' message and startling loud noise appear.

Line: https://github.com/Blackvoxel/Blackvoxel/blob/9e872c075e33a6b0f5e6c27cf2fd6b981da5886e/src/ZTool_Constructor.cpp#L263

**Comment by Blackvoxel** [comment]
Hi, Asl97
Thanks for signaling this bug. 
We have reproduced it successfully. We'll fix it. 
Best regards,
The Blackvoxel Team
