### ISSUE TITLE
Dragging from side bar to the same slot in inv delete item

### ISSUE THREAD

**Issue by asl97** [Blackvoxel/Blackvoxel#24]
Dragging from side bar to the same slot in inventory (and the other way too) delete item.

It was mostly an accident discovery.
____
There are a number of other problem with the side bar too, maybe it should be non draggable.

For example:
http://forum.blackvoxel.com/index.php?topic=15.msg45#msg45
```
Even when the mouse is hidden in the game, you can still drag and drop the icons on the right toolbar. 
```

**Comment by Blackvoxel** [comment]
Hi Asl97,
Thanks for reporting these bugs about the bar.
We reproduced them successfully. 
Making the items on the bar non-draggable sounds like a good idea.
Best regards,
The Blackvoxel Team
