### ISSUE TITLE
Non-empty storage absorption is not protected from other storages

### ISSUE THREAD

**Issue by tYYGH** [Blackvoxel/Blackvoxel#28]
I had the habit of creating a chain like this:
```
            +---------+         +---------+---------+
Insertion   |         |         |         |         |
of input  → |Base Tool|  Empty… |Demat…zer| Storage |
voxels      |         |         |         |         |
            +---------+         +---------+---------+
```

This way, series of 32 or 64 products are automatically stored, and can be more easily transferred into the Inventory in one move.
Until one day I had no storage left, and I produced new ones…

I knew I would obtain this:

```
            +---------+---------+---------+---------+
Insertion   |         |  (new)  |         |  (full) |
of input  → |Base Tool| Storage |Demat…zer| Storage |
voxels      |         |         |         |         |
            +---------+---------+---------+---------+
```

I thought: no problem, a non-empty storage cannot be absorbed, so it will absorb the new, empty, ones.
Alas, the reverse happened: the first empty storage absorbed the full one, and I lost everything inside :-o

**Comment by Blackvoxel** [comment]
Yes, this is roughly that kind of working.

Here is the precise algorithm:

- The algorithm is cycling through the 6 directions.
- For each direction, looking first for a storage.
- If a storage is found, then looking at the oposite side for a "disintegrable" voxel.
- If the two above conditions was meet, disintegrate the voxel and put it in the storage.

The 6 directions sequence is not the (0,1,2,3,4,5) sequence shown in the Alignement Voxel but this one :

0 : x-1
1 : x+1
2 : y-1
3 : y+1
4 : z-1
5 : z+1

Warning:  Universe use the video game convention : y=vertical, not z.

In the hope we have answered to your questions.

The Blackvoxel Team

**Comment by tYYGH** [comment]
Perfect :-) Cheers
