### ISSUE TITLE
Error in main.cpp

### ISSUE THREAD

**Issue by tYYGH** [Blackvoxel/Blackvoxel#29]
Please see here:
https://aur.archlinux.org/packages/blackvoxel/#news

Apparently `glext.h` should not be included any more…

**Comment by Blackvoxel** [comment]
Hi, tYYGH ,

Thanks for signaling this issue.

The team will investigate the problem.

Thanks again,
The Blackvoxel Team

**Comment by Blackvoxel** [comment]
I appears this issue was fixed some time ago by b81f0bd5c553416f69e3867e41c06e7c25501e78
So, closing.
