### ISSUE TITLE
Up and down keys are Q and Z regardless of keymap settings.

### ISSUE THREAD

**Issue by 0joshuaolson1** [Blackvoxel/Blackvoxel#3]
That is, in school mode. And I'm sure the dozen or so undocumented key bindings are hardcoded too at the mo'.

**Comment by Blackvoxel** [comment]
Thanks for signaling this problem.
We'll track this issue and the upcoming V1.38 will be fixed for that. It will be out in few time.
Don't hesistate to let us know when this version will get out in the case the problems remains.
The Blackvoxel Team

**Comment by 0joshuaolson1** [comment]
Thanks for fixing this!
