### ISSUE TITLE
Exits at runtime with error "Failed to load random file"

### ISSUE THREAD

**Issue by katp32** [Blackvoxel/Blackvoxel#34]
Compiled from source, on Linux, release 2.41. Full output:

```
Starting BlackVoxel...
Error loading random file
terminate called without an active exception
```

**Comment by Blackvoxel** [comment]
Hello katp32,

This error means that the Blackvoxel program has not found its data files (the randomnum.dat file)

As the default build configuration, Blackvoxel is searching it's data files in the current directory. 

So, Blackvoxel should run if you type

```
make clean
make
./blackvoxel
```
After that, you'll have to cd to this directory if you want to launch it.

`cd /home/me/blackvoxel_living_directory && ./blackvoxel`

In the case you want to install the blackvoxel files in some fixed location, (let's say in /opt/blackvoxel), you have to build it using the following commands

```
make clean
make blackvoxeldatadir=/opt/blackvoxel
```

Now, the blackvoxel program will look for it's data files in this fixed location. You can install the executable in the location of your choice.

In the hope we have answered your question.
The Blackvoxel Team

**Comment by katp32** [comment]
Indeed, I am aware. I'm building with `make blackvoxeldatadir="/usr/share/blackvoxel/"`, and of course installing the data files to that directory.

**Comment by katp32** [comment]
The following build settings also fail to set the correct data location:

- `make blackvoxeldatadir="/usr/share/blackvoxel"`
- `make blackvoxeldatadir=/usr/share/blackvoxel`
- `make blackvoxeldatadir=/usr/share/blackvoxel/`

So it seems it is not just a minor issue with the Makefile adding quotes...

**Comment by Blackvoxel** [comment]
We have reworked the makefile and updated it on github some hours ago. 

A lot of things was changed. The "blackvoxeldatadir" argument isn't working anymore.

The new way to use it :

```
make clean
make BV_DATA_LOCATION_DIR=/usr/share/blackvoxel
make install doinstall=true BV_DATA_INSTALL_DIR=/usr/share/blackvoxel BV_BINARY_INSTALL_DIR=/usr/bin

```
To be sure it's working, we have tested it on a completely fresh Ubuntu 20.04.1 install.

Here is the complete script we used to test. We confirmed it's result was ok. Blackvoxel was installed and ran ok from the installed location.

```
#!/bin/sh
sudo apt-get install build-essential libglew-dev libsdl1.2-dev git
cd ~
mkdir Blackvoxel_Source
cd Blackvoxel_Source
git clone https://github.com/Blackvoxel/Blackvoxel.git
cd Blackvoxel
make BV_DATA_LOCATION_DIR=/usr/share/blackvoxel
sudo make install doinstall=true BV_DATA_INSTALL_DIR=/usr/share/blackvoxel BV_BINARY_INSTALL_DIR=/usr/bin
blackvoxel

```

**Comment by katp32** [comment]
Probably `BV_DATA_INSTALL_DIR` and `BV_BINARY_INSTALL_DIR` should respect the value of `DESTDIR`...

**Comment by katp32** [comment]
Ah, nevermind, I misread the Makefile; thanks for the quick fix!
