### ISSUE TITLE
A lot of warnings with GCC-11

### ISSUE THREAD

**Issue by tastytea** [Blackvoxel/Blackvoxel#36]
GCC-11 switched the default to `-std=gnu++17`. This leads to a lot of warnings when compiling Blackvoxel:

```
In file included from src/z/ZTypes.h:90,
                 from src/Z3DBlit.h:38,
                 from src/Z3DBlit.cpp:27:
src/z/ZType_ZVector3d.h: In member function ‘double ZVector3d::Distance(ZVector3d&)’:
src/z/ZType_ZVector3d.h:291:21: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
  291 |     register double t1,t2;
[…]
```

Full log: [games-action:blackvoxel-2.42:20210503-013027.log](https://github.com/Blackvoxel/Blackvoxel/files/6412618/games-action.blackvoxel-2.42.20210503-013027.log) (~7 MiB)

Adding `-std=c++14` to the build flags silences these warnings.

**Comment by Blackvoxel** [comment]
Hello Tastytea

Thanks for signaling this issue.

We'll investigate about this problem. It appears we have to make some choices. 

Likely we'll do some fix for the upcoming release. It's coming very soon with a lot of new stuff ;)

Best regards,
The Blackvoxel Team

**Comment by thesamesam** [comment]
Looks like this was fixed by https://github.com/Blackvoxel/Blackvoxel/commit/51aa78b399e136129d91f001b8ef3e4e8c1e8df6.

**Comment by Blackvoxel** [comment]
Thanks for signaling this.
Yes, this was fixed. 
We just made a test to be sure and it's ok.
So closing this bug.
