### ISSUE TITLE
Use annotated tags for new releases.

### ISSUE THREAD

**Issue by patlefort** [Blackvoxel/Blackvoxel#37]
This way, notifications can be sent by github about new releases. If you prefer, you can also use the [github web page to create a release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository). It is useful for packagers to track new releases.

**Comment by Blackvoxel** [comment]
Thanks for your suggestion.

That's done.

We wish you a good day,
The Blackvoxel Team
