### ISSUE TITLE
Game crashes due to segmentation fault on Arch Linux

### ISSUE THREAD

**Issue by something12356** [Blackvoxel/Blackvoxel#40]
I'm using an up to date build of Arch Linux with a Radeon 6600xt GPU. The game will run and successfully show a loading screen, and then crashes due to segmentation fault. This occurs both with the AUR package of the game, and when I compile the game myself from source using the make command. Any ideas what might be causing this?

**Comment by Blackvoxel** [comment]
Hello and thanks for your interest in Blackvoxel.

Unfortunately, at first glance, we have no idea about the cause of this crash.

The actual code of Blackvoxel is very stable, wasn't modified recently and that's the first report we received about this.

Even if we don't see evident cause for this crash, this could be related to some regressions on external library or some configuration problems.

As a first step, you can show us the content of the log.txt file that Blackvoxel generate at launch as it show each point of the game startup sequence that was successfully completed. That could show in which point the sequence crashed.

Some other questions that might be usefull :

Have you already launched other OpenGL games on this machine ? (Maybe something like Warzone 2100).

Have you tried the game on another machine ?

We wish you best regards and are sorry that you encounter problem with our game.

The Blackvoxel Team

**Comment by something12356** [comment]
Thank you, that works!
