### ISSUE TITLE
Busy loop in ZSectorStreamLoader.cpp

### ISSUE THREAD

**Issue by asl97** [Blackvoxel/Blackvoxel#6]
High cpu usage cause by busy loop in ZSectorStreamLoader.cpp.
____
cause by thread created by https://github.com/Blackvoxel/Blackvoxel/blob/cac5f123dd0badc32da4d3b6142d584d7b9275f6/src/ZSectorStreamLoader.cpp#L133

solution, uncomment this line: https://github.com/Blackvoxel/Blackvoxel/blob/cac5f123dd0badc32da4d3b6142d584d7b9275f6/src/ZSectorStreamLoader.cpp#L66

**Comment by Blackvoxel** [comment]
Hi asl97,

We confirm you have found an important bug.

Thanks a lot for your useful bug report.

Best regards,

The Blackvoxel Team
